// <auto-generated />
namespace ZeroHunger_Asg.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FoodEdittest3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FoodEdittest3));
        
        string IMigrationMetadata.Id
        {
            get { return "202303211746260_FoodEdittest3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
